booking/urls.py
from django.urls import path
from .views import InterviewCreateView

app_name = 'booking'

urlpatterns =[
    path('create-interview/<int:pk>/', InterviewCreateView.as_view(), name='interview-create'),
]

byp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photographers/', include('photographer.urls')),
    path('chat/', include('chat.urls')),
    # path('customers/', include('customer.urls')),
    path('booking/', include('booking.urls')),
    path('', include('pages.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

photographer/urls.py
from django.urls import path
from .views import PhotographerListView, PhotographerDetailView

app_name = 'photographer'

urlpatterns=[
    path('', PhotographerListView.as_view(), name='photographers'),
    path('photographer/<int:pk>/', PhotographerDetailView.as_view(), name='photographer-detail'),
]

photographer/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

from customer.models import Customer

# class Portfolio(models.Model):
#     images = models.ImageField(upload_to='portfolio/')

#     def __str__(self):
#         return f"{self.images}"
    
#     def get_absolute_url(self):
#         return reverse('portfolio_detail', args=[str(self.id)])

class Rating(models.Model):
    rating = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])

    class Meta:
        ordering = ['rating']

    def __str__(self):
        return f"{self.rating}"

class Photographer(models.Model):
    PHOTOGRAPHY_GENRE = [
    ('Adventure Photography', 'Adventure Photography'),
    ('Aerial Photography', 'Aerial Photography'),
    ('Astro Photography', 'Astro Photography'),
    ('Automotive Photography', 'Automotive Photography'),
    ('Commercial Photography', 'Commercial Photography'),
    ('Documentary Photography', 'Documentary Photography'),
    ('Event Photography', 'Event Photography'),
    ('Fashion Photography', 'Fashion Photography'),
    ('Fine Art Photography', 'Fine Art Photography'),
    ('Food Photography', 'Food Photography'),
    ('Industrial Photography', 'Industrial Photography'),
    ('Landscape Photography', 'Landscape Photography'),
    ('Medical Photography', 'Medical Photography'),
    ('Pet Photography', 'Pet Photography'),
    ('Photojournalist', 'Photojournalist'),
    ('Portrait Photography', 'Portrait Photography'),
    ('Product Photography', 'Product Photography'),
    ('Real Estate Photography', 'Real Estate Photography'),
    ('Scientific Photography', 'Scientific Photography'),
    ('Sports Photography', 'Sports Photography'),
    ('Stock Photography', 'Stock Photography'),
    ('Street Photography', 'Street Photography'),
    ('Travel Photography', 'Travel Photography'),
    ('War Photography', 'War Photography'),
    ('Wedding Photography', 'Wedding Photography'),
    ('Wildlife Photography', 'Wildlife Photography'),
    ]
    first_name = models.CharField(max_length=50, help_text="Enter first name")
    last_name = models.CharField(max_length=50, help_text="Enter last name")
    email = models.EmailField(max_length=200, null=True)
    phone_no = models.CharField(max_length=50, null=True)
    description = models.TextField(max_length=1000, null=True)
    profile_pic = models.ImageField(upload_to='profile_pic/', null=True)
    category = models.CharField(max_length=100, choices=PHOTOGRAPHY_GENRE, null=True)
    # portfolio = models.ForeignKey(Portfolio, on_delete=models.SET_NULL, null=True)
    rating = models.ForeignKey(Rating, null=True, on_delete=models.SET_NULL)
    rate = models.CharField(max_length=100, blank=True, null=True, verbose_name='Fees')
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now= True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    
    def __str__(self):

        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name
    
    def get_absolute_url(self):
        return reverse('photographer_detail', args=[str(self.id)])


def upload_to_directory(instance, filename):

    if instance.photographer:
        return f'portfolio/{instance.photographer}/{filename}'
    else:
        return f'portfolio/unknown photographers/{filename}'


class Portfolio(models.Model):
    photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to=upload_to_directory, blank=True, null=True)

    def __str__(self):
        return f"{self.photographer}'s portfolio" if self.photographer else "Unassigned Portfolio"

class Review(models.Model):
    photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE, null=True)
    comments = models.TextField(max_length=1000, null=True)
    created_by = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    created_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Comment: {self.comment} by {self.created_by} for {self.photographer}"
    
    def get_absolute_url(self):
        return reverse('reiew_detail', args=[str(self.id)])

photographer/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView
from .models import Photographer, Portfolio, Rating

class PhotographerListView(ListView):
    model = Photographer
    template_name = 'photographer/photographer_list.html'
    paginate_by = 12
    context_object_name = 'photographers'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.GET.get('search')
        if search_term:
            queryset=queryset.filter(
                Q(first_name__icontains=search_term)|
                Q(last_name__icontains=search_term)|
                Q(category__icontains=search_term)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.model.objects.all()
        search_term = self.request.GET.get('search')
        if search_term:
            queryset=queryset.filter(
                Q(first_name__icontains=search_term)|
                Q(last_name__icontains=search_term)|
                Q(category__icontains=search_term)
            ) 
            if not queryset.exists():
                context['no_results']=f'No match found for "{search_term}"'  
        context['search_term']=search_term
        return context
    

class PhotographerDetailView(DetailView):
    model = Photographer
    template_name = "photographer/photographer_detail.html"
 
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        photographer = self.get_object()
        photographer_portfolio = Portfolio.objects.filter(photographer=photographer)
        if photographer_portfolio:
            context['portfolio'] = photographer_portfolio
        else:
            context['no_portfolio'] = f"Portfolio not available for {photographer}."
        return context

photographer/templates/photographer/photographer_detail.html
{% extends "frontend/homepage.html" %}
{% load static %}

{% block content %}
<main>
<div class="container my-5">
    <section class="row p-4 pb-4 pe-lg-0 pt-lg-4 justify-content-center rounded-3 border shadow-lg">
      <div class="row py-lg-5">
        <div class="col-3 mx-auto">
          <div class="mb-2">
            <img class="rounded" src="{{ photographer.profile_pic.url }}" alt="{{photographer.first_name}}'s pfp" style="width: 250px; height: 250px; object-fit: cover; margin: 10px;">
          </div>
        </div>
        <div class="col-9 mx-auto">
          <h1 class="fw-light"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{photographer}}</font></font></h1>
            <p class="lead text-body-secondary"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{photographer.description}}</font></font></p>
          <p>
            <p class="badge bg-light text-success"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{photographer.email}}</font></font></p>
            <p class="badge bg-light text-warning"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{photographer.phone_no}}</font></font></p>
            <p class="badge bg-light text-success"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{photographer.rating}}</font></font></p>
            <p class="badge bg-light text-warning"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{photographer.rate}}/hr</font></font></p>
          </p>
          <div class="d-block">
            <a href="{% url 'booking:interview-create' photographer.id %}" class="btn btn-success btn-sm">Book an Interview</a>
            <a href="" class="btn btn-warning btn-sm">Book a Session</a>
          </div>
        </div>
      </div>
    </section>
</div>  
    <div class="album py-5 bg-body-tertiary">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% if portfolio %}  
              {% for x in portfolio %}
                <div class="col">
                  <div class="card shadow">
                    <img class="bd-placeholder-img card-img-top portfolio-image-thumbnail" width="100%" height="225" src="{{ x.image.url }}" role="img" data-bs-toggle="modal" data-bs-target="#imageViewModal" data-image="{{ x.image.url }}" preserveAspectRatio="xMidYMid slice" style="cursor: pointer;">
                  </div>
                </div>
              {% endfor %}
            {% elif no_portfolio %}
              <div class="alert alert-warning w-25" role="alert">
                {{no_portfolio}}
              </div>
            {% endif %}
            <!-- Modal -->
            <div class="modal fade" id="imageViewModal" tabindex="-1" aria-labelledby="imageViewModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered"> 
                  <div class="modal-content">
                      <div class="modal-header">
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body text-center">
                          <img id="imageForModal" src="" alt="Portfolio Image" style="max-width: 100%; height: auto;"> <!-- Adjust max-width to 100% to make the image larger -->
                      </div>
                  </div>
              </div>
            </div><!-- Modal End -->
        </div>
      </div>
    </div>
  </main>
{% endblock %}
{% block javascript %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
        $(".portfolio-image-thumbnail").on("click", function() {  
            var imageUrl = $(this).data("image");
            $("#imageForModal").attr("src", imageUrl);
            console.log("the passed image url is:", imageUrl);
        });
    });
    
  </script>
{% endblock javascript %}

photographer/templates/photographer/photographer_list.html
{% extends "frontend/homepage.html" %}
{% load static %}
{% block css %}
{% endblock %}

        <link rel="shortcut icon" href="assets/images/favicon.ico">
    
        <!-- Bootstrap Css -->
        <link href="{% static 'static/assets/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'static/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'static/assets/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css"> 

{% block content %}
<div style="background-color: #f9f9f9;">
    <div class="container my-5">
        <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
          <div class="col-sm-8 py-5 mx-auto">
            <h1 style="display-5 fw-normal">Find your photographer – search, connect, book.</h1>
                <form method='GET' action="{% url 'photographer:photographers' %}">
                    <div class="d-flex justify-content-center" style="margin: 15px; padding:25px;"> 
                        <input class="form-control search mr-sm-2 w-50" type="search" placeholder="Search your photographer" {% if search_term %} value= {{ search_term }} {% endif %} name='search'>
                        <button class="btn btn-outline-secondary" type="submit" style="margin-left: 3px; border: none;"><i class="bi bi-search">Search</i> </button>
                    </div> 
                    {% if no_results %}
                    <div class="d-flex justify-content-center">
                        <div class="alert alert-info w-50">
                            {{ no_results }}
                        </div>
                    </div>
                    {% endif %}            
                </form>
            </div>
        </div>
      </div>
</div>

<div class="container" style="margin-top: 50px; background-color: #f9f9f9;">
    <div class="row" style="display: grid; grid-template-columns: repeat(3, 1fr); grid-gap: 10px;">
        {% for photographer in photographers %}            
        <div class="card rounded-3 border shadow-lg">
            <div class="d-block justify-content-center">
                <a href="{% url 'photographer:photographer-detail' photographer.id %}" class="text-decoration-none text-dark">
                    <div class="card-body">
                        <div class="card-header-profile-user d-flex justify-content-center mt-2">
                            <h4 class="card-title">{{photographer.first_name}} {{photographer.last_name}}</h4>
                        </div>
                        <div class="d-flex justify-content-center">
                            <p class="badge rounded-pill bg-light text-dark">{{photographer.category}}</p>
                        </div>
                        <div class="d-flex justify-content-center">
                            <img class="rounded-circle" src="{{ photographer.profile_pic.url }}" alt="{{photographer.first_name}}'s pfp" style="width: 100px; height: 100px; object-fit: cover; margin: 10px;">
                        </div>
                        <div class="d-flex justify-content-center m-2">
                            <p class="card-text">{{photographer.description}}</p>
                        </div>
                        <div class="d-flex justify-content-evenly m-2">
                            <span class="badge bg-warning-subtle text-dark">{{photographer.email}}</span>
                            <span class="badge bg-warning-subtle text-dark">{{photographer.phone_no}}</span>
                            <span class="badge bg-warning-subtle text-dark">{{photographer.rating}}</span>
                            <span class="badge bg-warning-subtle text-dark">{{photographer.rate}}/hr</span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div><!-- end col -->   
</div>
</div>
{% endblock %}